language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
install:
    - "pip install -q -e . --use-mirrors"
env: SECRET_KEY=justfortravis
script: "py.test --pep8"
notifications:
    email:
        recipients:
            - info@nsupdate.info
