language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
env:
    global:
      - SECRET_KEY=justfortravis
      - DNS_RESOLVER_TIMEOUT=15.0
      - DNS_UPDATE_TIMEOUT=30.0
    matrix:
      - DJANGO=1.5.5
      - DJANGO=1.6.1
install:
    - "pip install --use-mirrors Django==$DJANGO"
    - "pip install --use-mirrors -e ."
    - "pip install --use-mirrors coveralls"
script: "coverage run -m py.test --pep8"
after_success:
    - coveralls
notifications:
    email:
        recipients:
            - info@nsupdate.info
