language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
    - "3.3"
    - "3.4"
env:
    global:
      - SECRET_KEY=justfortravis
      - DNS_RESOLVER_TIMEOUT=15.0
      - DNS_UPDATE_TIMEOUT=30.0
      - TEST_K="not dnstools and not ddns_client"
      - TEST_OPTS=""
      - COVERAGE=""
    matrix:
      - DJANGO=1.5.9
      - DJANGO=1.6.6
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=1.6.6
  include:
    - python: "2.7"
      env: DJANGO=1.6.6 COVERAGE="coverage run -m" TEST_K="" TEST_OPTS="--pep8"
install:
    - "pip install --use-mirrors Django==$DJANGO"
    - "pip install --use-mirrors -e ."
    - "pip install --use-mirrors coveralls"
script: $COVERAGE py.test $TEST_OPTS -k "$TEST_K"
after_success:
    - coveralls
notifications:
    email:
        recipients:
            - info@nsupdate.info
