language: python
python:
    - "2.7"
    - "pypy"
install:
    - "pip install --upgrade --use-mirrors -e ."
env: SECRET_KEY=justfortravis
script: "py.test --pep8"
notifications:
    email:
        recipients:
            - info@nsupdate.info
