language: python
python:
    - "2.7"
    - "pypy"
    - "3.4"
    - "3.5"
env:
    global:
      - SECRET_KEY=justfortravis
      - DNS_RESOLVER_TIMEOUT=15.0
      - DNS_UPDATE_TIMEOUT=30.0
      - TEST_K="not dnstools and not ddns_client"
      - TEST_OPTS=""
      - COVERAGE=""
    matrix:
      - DJANGO=1.8.1
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=1.8.1
  include:
    - python: "2.7"
      env: DJANGO=1.8.1 COVERAGE="coverage run -m" TEST_K="" TEST_OPTS="--pep8"
install:
    - "pip install Django==$DJANGO"
    - "pip install -r requirements.d/travis.txt"
    - "pip install -e ."
script: $COVERAGE py.test $TEST_OPTS -k "$TEST_K" -m "not requires_sequential"
after_success:
    - coveralls
notifications:
    email:
        recipients:
            - info@nsupdate.info
